Repository Candidate-College/candidate-careers-api, pull requests merged in 2025-07, with the labels that each got.

#1 feat: migration scripts from ERD
  .dockerignore
  docker/api/Dockerfile
  docs/api.html
  docs/request-validation.md
  docs/v1.yaml
  src/app.ts
  src/database/migrations/20250509062123_roles.ts
  src/database/migrations/20250509062124_users.ts
  src/database/migrations/20250509062125_password_reset_tokens.ts
  src/database/migrations/20250509062125_user_sessions.ts
  src/database/migrations/20250509062126_email_notifications.ts
  src/database/migrations/20250509062126_user_verifications.ts
  src/database/migrations/20250509062127_activity_logs.ts
  src/database/migrations/20250509062128_job_categories.ts
  src/database/migrations/20250509062129_departments.ts
  src/database/migrations/20250509062130_job_postings.ts
  src/database/migrations/20250509062131_sessions.ts
  src/database/migrations/20250509062132_system_settings.ts
  src/database/migrations/20250509062133_monthly_analytics.ts
  src/database/migrations/20250509062134_job_views.ts
  src/database/migrations/20250509062135_applications.ts
  src/database/migrations/20250509062136_application_notes.ts
  src/database/migrations/20250509070456_event_categories.ts
  src/database/migrations/20250509070457_events.ts
  src/middlewares/request-validation-middleware.ts
  src/routes/docs.ts
  src/routes/index.ts
  src/utilities/logger.ts
  src/validators/job-form-validator.ts
Labels: enhancement

#5 feat: comprehensive super admin user management—update, bulk ops, reset password, impersonation, and tests
  docs/v1.yaml
  logs/audit.log
  package-lock.json
  package.json
  src/controllers/audit-controller.ts
  src/controllers/audit-export-controller.ts
  src/controllers/user-management-controller.ts
  src/interfaces/user/user-management.ts
  src/middlewares/activity-logger.ts
  src/middlewares/rateLimiter.ts
  src/models/user-model.ts
  src/repositories/role-permission-repository.ts
  src/repositories/user-repository.ts
  src/routes/v1/admin/index.ts
  src/routes/v1/admin/user-management-routes.ts
  src/routes/v1/index.ts
  src/services/audit/activity-analytics-service.ts
  src/services/audit/activity-categorization.ts
  src/services/email/email-service.ts
  src/services/user/user-activity-service.ts
  src/services/user/user-impersonation-service.ts
  src/services/user/user-management-service.ts
  src/services/user/user-search-service.ts
  src/utilities/password-generator.ts
  src/utilities/winston-logger.ts
  src/validators/user/bulk-operations.validator.ts
  src/validators/user/create-user.validator.ts
  src/validators/user/delete-user.validator.ts
  src/validators/user/impersonate-user.validator.ts
  src/validators/user/list-users.validator.ts
  src/validators/user/reset-password.validator.ts
  src/validators/user/search-users.validator.ts
  src/validators/user/update-user.validator.ts
  src/validators/user/user-uuid.validator.ts
  tests/integration/user-management-api.integration.test.ts
  tests/repositories/user-repository.detail.test.ts
  tests/repositories/user-repository.test.ts
  tests/resources/activity-log-resource.test.ts
  tests/services/audit/activity-metadata.test.ts
  tests/services/user-activity-service.test.ts
  tests/services/user-impersonation-service.test.ts
  tests/services/user-management-service.test.ts
  tests/services/user-search-service.test.ts
  tsconfig.json
  types/bcrypt.d.ts
  types/mock-knex.d.ts
  types/nodemailer.d.ts
Labels: bug, documentation, enhancement

#8 feat: implement robust, idempotent, and profile-less database seeders with error handling, reset, and performance tests
  package.json
  src/database/migrations/20250509062128_job_categories.ts
  src/database/migrations/20250509062129_departments.ts
  src/database/migrations/20250509062130_job_postings.ts
  src/database/migrations/20250509062135_applications.ts
  src/database/migrations/20250509062136_application_notes.ts
  src/database/seeders/02_users.ts
  src/database/seeders/20250715083000_default_roles_permissions.ts
  src/database/seeders/20250721230501_roles.ts
  src/database/seeders/20250721230502_users.ts
  src/database/seeders/20250721230503_departments.ts
  src/database/seeders/20250721230504_job-categories.ts
  src/database/seeders/20250721230505_job-postings.ts
  src/database/seeders/20250721230506_applications.ts
  src/database/seeders/20250721230507_application-notes.ts
  src/utilities/seeder-utils.ts
  tests/database/seeders/seeder-integrity.test.ts
  tests/database/seeders/seeder-reset.test.ts
  tests/database/seeders/seeder-suite.test.ts
  tests/database/seeders/seeder-validation.test.ts
Labels: documentation, enhancement
